# Generated by Django 3.0.8 on 2020-07-18 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hod', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('staff_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('Sir', 'Sir'), ('MS', 'Ms'), ('DR', 'Dr'), ('PROF.', 'Prof'), ('REV', 'Rev'), ('NOT SPECIFIED', 'not specified')], default='not specified', max_length=50)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('other_name', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT SPECIFIED', 'not specified')], default='not specified', max_length=20)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('NOT SPECIFIED', 'not specified')], default='not specified', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=250, null=True)),
                ('home_town', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=250, null=True)),
                ('institution', models.CharField(blank=True, max_length=250, null=True)),
                ('special_role', models.CharField(blank=True, max_length=250, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu.Department')),
            ],
        ),
    ]
