# Generated by Django 3.0.8 on 2020-07-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20200719_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nhis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('nhis_scheme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT SPECIFIED', 'not specified')], max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('NOT SPECIFIED', 'not specified')], default='not specified', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
