# Generated by Django 3.0.8 on 2020-07-25 09:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0008_druginventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupPassword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu.Staff')),
            ],
        ),
    ]
