# Generated by Django 3.0.8 on 2020-07-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0009_setuppassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setuppassword',
            old_name='staff_id',
            new_name='staff',
        ),
    ]
