# Generated by Django 3.0.8 on 2020-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0010_auto_20200725_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuppassword',
            name='staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
