# Generated by Django 3.0.8 on 2020-07-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0011_auto_20200725_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setuppassword',
            old_name='staff',
            new_name='staff_id',
        ),
    ]
