# Generated by Django 3.0.8 on 2020-07-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0012_auto_20200725_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginventory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Department'),
        ),
    ]
