# Generated by Django 3.0.8 on 2020-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0013_auto_20200725_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginventory',
            name='signatory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
