# Generated by Django 3.0.8 on 2020-07-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0017_auto_20200730_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='nhis_available',
        ),
    ]
