# Generated by Django 3.0.8 on 2020-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0018_remove_billing_nhis_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('NON_STUDENT', 'Non Student')], default='NOT SPECIFIED', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NOT SPECIFIED', 'not specified')], default='NOT SPECIFIED', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
