# Generated by Django 3.0.8 on 2020-08-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0022_auto_20200806_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='physician_name',
            new_name='staff',
        ),
    ]
