# Generated by Django 3.0.8 on 2020-08-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0023_auto_20200807_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppassword',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Role'),
        ),
        migrations.AlterField(
            model_name='druginventory',
            name='drug_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.Staff'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type_of_patient',
            field=models.CharField(choices=[('student', 'Student'), ('non student', 'Non Student'), ('not specified', 'not specified')], default='NOT SPECIFIED', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
