# Generated by Django 3.0.8 on 2020-08-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0024_auto_20200807_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setuppassword',
            old_name='role',
            new_name='role_name',
        ),
    ]
