# Generated by Django 3.0.8 on 2020-08-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0026_auto_20200807_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setuppassword',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.Role'),
        ),
    ]
