# Generated by Django 3.0.8 on 2020-08-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0027_auto_20200808_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setuppassword',
            name='role',
        ),
    ]
