# Generated by Django 3.0.8 on 2020-08-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0028_remove_setuppassword_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='setuppassword',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setuppassword',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
