# Generated by Django 3.0.8 on 2020-08-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0030_billing_cost_of_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='cost_of_service',
            field=models.FloatField(default=0.0, help_text='NOTE: for non student only'),
        ),
    ]
